name: braunonsite
concurrency: braunonsite

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: braunonsite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login into ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_ACR_REGISTRY }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep